language: csharp
mono: none
dotnet: 2.0.0
script:
- dotnet restore
- dotnet build ./FizzBuzzer/
- dotnet test ./FizzBuzzer.Tests/
notifications:
    email:
        on_success: never
        on_failure: always